---
spring:
  datasource:
#    url: jdbc:mysql://test-m1-mysql.local-lwjr.com:3306/fund_ta?useUnicode=true&characterEncoding=utf-8
#    username: order_t_w
#    password: NTk3NjIyYmJmNDY
#    url: jdbc:mysql://10.75.229.93:3306/fund_ta?useUnicode=true&characterEncoding=utf-8
#    username: order_t_w
#    password: J_mtpJxVtbF3PJ
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: zheng
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
#    meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    default-executor-type: simple
    map-underscore-to-camel-case: true
    local-cache-scope: session
    jdbc-type-for-null: null